/*
Confluent Cloud APIs

Testing PartitionV3ApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/shono-io/shono-ccloud"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_PartitionV3ApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PartitionV3ApiService GetKafkaPartition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var clusterId string
		var topicName string
		var partitionId int32

		resp, httpRes, err := apiClient.PartitionV3Api.GetKafkaPartition(context.Background(), clusterId, topicName, partitionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PartitionV3ApiService ListKafkaPartitions", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var clusterId string
		var topicName string

		resp, httpRes, err := apiClient.PartitionV3Api.ListKafkaPartitions(context.Background(), clusterId, topicName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
