/*
Confluent Cloud APIs

Testing PluginsV1ApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_PluginsV1ApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PluginsV1ApiService ListConnectv1ConnectorPlugins", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var environmentId string
		var kafkaClusterId string

		resp, httpRes, err := apiClient.PluginsV1Api.ListConnectv1ConnectorPlugins(context.Background(), environmentId, kafkaClusterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PluginsV1ApiService ValidateConnectv1ConnectorPlugin", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pluginName string
		var environmentId string
		var kafkaClusterId string

		resp, httpRes, err := apiClient.PluginsV1Api.ValidateConnectv1ConnectorPlugin(context.Background(), pluginName, environmentId, kafkaClusterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
