/*
Confluent Cloud APIs

Testing ModesV1ApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/shono-io/shono-ccloud"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_ModesV1ApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ModesV1ApiService DeleteSubjectMode", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var subject string

		resp, httpRes, err := apiClient.ModesV1Api.DeleteSubjectMode(context.Background(), subject).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ModesV1ApiService GetMode", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var subject string

		resp, httpRes, err := apiClient.ModesV1Api.GetMode(context.Background(), subject).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ModesV1ApiService GetTopLevelMode", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ModesV1Api.GetTopLevelMode(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ModesV1ApiService UpdateMode", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var subject string

		resp, httpRes, err := apiClient.ModesV1Api.UpdateMode(context.Background(), subject).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ModesV1ApiService UpdateTopLevelMode", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ModesV1Api.UpdateTopLevelMode(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
